# ----------------------------
# Makefile Options
# ----------------------------

NAME = PONG
ICON = icon.png
DESCRIPTION = "Pong game"
COMPRESSED = YES
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Os
CXXFLAGS = -Wall -Wextra -Os

# ----------------------------

include $(shell cedev-config --makefile)
